name: "markdown-to-pdf-ja"
description: "make pdf from md by pandoc"
inputs:
  DEFAULT_FILE: # id of input
    description: "default file of pandoc"
    required: true
    default: "report"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.DEFAULT_FILE }}
