on: [push]

jobs:
  pandoc-job:
    runs-on: ubuntu-latest
    name: a job to pandoc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: pandoc action step
        uses: Amusac/markdown-to-pdf-ja@dev
        with:
          input-file: "input.md"
      - name: ls
        run: ls .
