on: [push]

jobs:
  pandoc-job:
    runs-on: ubuntu-latest
    name: a job to pandoc
    steps:
      - name: pandoc action step
        uses: Amusac/markdown-to-pdf-ja
        id: pandoc
        with:
          input-file: "input.md"
